# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'L:\Python Projekte\Galabau-2\Ui\Wizard\Projects\wizardStartPage.ui'
#
# Created: Thu Oct 11 00:38:19 2012
#      by: PyQt4 UI code generator 4.9.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_WizardPage(object):
    def setupUi(self, WizardPage):
        WizardPage.setObjectName(_fromUtf8("WizardPage"))
        WizardPage.resize(759, 396)
        self.verticalLayout_3 = QtGui.QVBoxLayout(WizardPage)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.frame_2 = QtGui.QFrame(WizardPage)
        self.frame_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_Datum_2 = QtGui.QLabel(self.frame_2)
        self.label_Datum_2.setMinimumSize(QtCore.QSize(100, 0))
        self.label_Datum_2.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_Datum_2.setFont(font)
        self.label_Datum_2.setObjectName(_fromUtf8("label_Datum_2"))
        self.horizontalLayout_4.addWidget(self.label_Datum_2)
        self.input_Projektnr = QtGui.QLineEdit(self.frame_2)
        self.input_Projektnr.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.input_Projektnr.setReadOnly(True)
        self.input_Projektnr.setObjectName(_fromUtf8("input_Projektnr"))
        self.horizontalLayout_4.addWidget(self.input_Projektnr)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_Datum = QtGui.QLabel(self.frame_2)
        self.label_Datum.setMinimumSize(QtCore.QSize(100, 0))
        self.label_Datum.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_Datum.setFont(font)
        self.label_Datum.setObjectName(_fromUtf8("label_Datum"))
        self.horizontalLayout.addWidget(self.label_Datum)
        self.input_Projektname = QtGui.QLineEdit(self.frame_2)
        self.input_Projektname.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.input_Projektname.setObjectName(_fromUtf8("input_Projektname"))
        self.horizontalLayout.addWidget(self.input_Projektname)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_Kunde = QtGui.QLabel(self.frame_2)
        self.label_Kunde.setMinimumSize(QtCore.QSize(100, 0))
        self.label_Kunde.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_Kunde.setFont(font)
        self.label_Kunde.setObjectName(_fromUtf8("label_Kunde"))
        self.horizontalLayout_3.addWidget(self.label_Kunde)
        self.input_Kunde = QtGui.QLineEdit(self.frame_2)
        self.input_Kunde.setReadOnly(True)
        self.input_Kunde.setObjectName(_fromUtf8("input_Kunde"))
        self.horizontalLayout_3.addWidget(self.input_Kunde)
        self.toolButton = QtGui.QToolButton(self.frame_2)
        self.toolButton.setObjectName(_fromUtf8("toolButton"))
        self.horizontalLayout_3.addWidget(self.toolButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_Status = QtGui.QLabel(self.frame_2)
        self.label_Status.setMinimumSize(QtCore.QSize(100, 0))
        self.label_Status.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_Status.setFont(font)
        self.label_Status.setObjectName(_fromUtf8("label_Status"))
        self.horizontalLayout_2.addWidget(self.label_Status)
        self.input_Status = QtGui.QComboBox(self.frame_2)
        self.input_Status.setObjectName(_fromUtf8("input_Status"))
        self.input_Status.addItem(_fromUtf8(""))
        self.input_Status.addItem(_fromUtf8(""))
        self.input_Status.addItem(_fromUtf8(""))
        self.horizontalLayout_2.addWidget(self.input_Status)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_Beschreibung = QtGui.QLabel(self.frame_2)
        self.label_Beschreibung.setMinimumSize(QtCore.QSize(100, 0))
        self.label_Beschreibung.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_Beschreibung.setFont(font)
        self.label_Beschreibung.setObjectName(_fromUtf8("label_Beschreibung"))
        self.verticalLayout.addWidget(self.label_Beschreibung)
        self.input_Beschreibung = QtGui.QTextEdit(self.frame_2)
        self.input_Beschreibung.setObjectName(_fromUtf8("input_Beschreibung"))
        self.verticalLayout.addWidget(self.input_Beschreibung)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)
        self.verticalLayout_3.addWidget(self.frame_2)

        self.retranslateUi(WizardPage)
        QtCore.QMetaObject.connectSlotsByName(WizardPage)

    def retranslateUi(self, WizardPage):
        WizardPage.setWindowTitle(QtGui.QApplication.translate("WizardPage", "WizardPage", None, QtGui.QApplication.UnicodeUTF8))
        WizardPage.setTitle(QtGui.QApplication.translate("WizardPage", "Neues Projekt", None, QtGui.QApplication.UnicodeUTF8))
        WizardPage.setSubTitle(QtGui.QApplication.translate("WizardPage", "Erstellt ein neues Projekt", None, QtGui.QApplication.UnicodeUTF8))
        self.label_Datum_2.setText(QtGui.QApplication.translate("WizardPage", "Projektnummer", None, QtGui.QApplication.UnicodeUTF8))
        self.label_Datum.setText(QtGui.QApplication.translate("WizardPage", "Projektname", None, QtGui.QApplication.UnicodeUTF8))
        self.label_Kunde.setText(QtGui.QApplication.translate("WizardPage", "Kunde", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton.setText(QtGui.QApplication.translate("WizardPage", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_Status.setText(QtGui.QApplication.translate("WizardPage", "Status", None, QtGui.QApplication.UnicodeUTF8))
        self.input_Status.setItemText(0, QtGui.QApplication.translate("WizardPage", "Offen", None, QtGui.QApplication.UnicodeUTF8))
        self.input_Status.setItemText(1, QtGui.QApplication.translate("WizardPage", "Abgerechnet", None, QtGui.QApplication.UnicodeUTF8))
        self.input_Status.setItemText(2, QtGui.QApplication.translate("WizardPage", "Geld erhalten", None, QtGui.QApplication.UnicodeUTF8))
        self.label_Beschreibung.setText(QtGui.QApplication.translate("WizardPage", "Beschreibung", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    WizardPage = QtGui.QWizardPage()
    ui = Ui_WizardPage()
    ui.setupUi(WizardPage)
    WizardPage.show()
    sys.exit(app.exec_())

