# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'L:\Python Projekte\Galabau-2\Ui\Kunden\kunden.ui'
#
# Created: Thu Oct 11 00:38:09 2012
#      by: PyQt4 UI code generator 4.9.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(822, 476)
        Form.setAutoFillBackground(False)
        self.verticalLayout_10 = QtGui.QVBoxLayout(Form)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.toolButton_new = QtGui.QToolButton(Form)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/newPrefix/res/1318968748_human-folder-public.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_new.setIcon(icon)
        self.toolButton_new.setIconSize(QtCore.QSize(35, 20))
        self.toolButton_new.setPopupMode(QtGui.QToolButton.DelayedPopup)
        self.toolButton_new.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_new.setAutoRaise(True)
        self.toolButton_new.setObjectName(_fromUtf8("toolButton_new"))
        self.verticalLayout_10.addWidget(self.toolButton_new)
        self.splitter = QtGui.QSplitter(Form)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.widget_2 = QtGui.QWidget(self.splitter)
        self.widget_2.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.widget_2)
        self.verticalLayout_9.setContentsMargins(0, 15, 0, 10)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.treeWidget = QtGui.QTreeWidget(self.widget_2)
        self.treeWidget.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.treeWidget.setFrameShape(QtGui.QFrame.NoFrame)
        self.treeWidget.setRootIsDecorated(False)
        self.treeWidget.setItemsExpandable(False)
        self.treeWidget.setObjectName(_fromUtf8("treeWidget"))
        self.treeWidget.header().setCascadingSectionResizes(True)
        self.treeWidget.header().setDefaultSectionSize(300)
        self.treeWidget.header().setSortIndicatorShown(True)
        self.verticalLayout_9.addWidget(self.treeWidget)
        self.frame_7 = QtGui.QFrame(self.splitter)
        self.frame_7.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_7.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_7.setObjectName(_fromUtf8("frame_7"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.frame_7)
        self.verticalLayout_4.setContentsMargins(0, 10, 0, -1)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.tabWidget = QtGui.QTabWidget(self.frame_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setUsesScrollButtons(False)
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.scrollArea = QtGui.QScrollArea(self.tab)
        self.scrollArea.setFrameShape(QtGui.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 770, 295))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setMargin(0)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.frame_6 = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.frame_6.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.frame_6.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_6.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_6.setObjectName(_fromUtf8("frame_6"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.frame_6)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.frame = QtGui.QFrame(self.frame_6)
        self.frame.setMinimumSize(QtCore.QSize(200, 0))
        self.frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.label = QtGui.QLabel(self.frame)
        self.label.setMinimumSize(QtCore.QSize(0, 20))
        self.label.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_6.addWidget(self.label)
        self.label_2 = QtGui.QLabel(self.frame)
        self.label_2.setMinimumSize(QtCore.QSize(0, 20))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_6.addWidget(self.label_2)
        self.label_3 = QtGui.QLabel(self.frame)
        self.label_3.setMinimumSize(QtCore.QSize(0, 20))
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_6.addWidget(self.label_3)
        self.label_4 = QtGui.QLabel(self.frame)
        self.label_4.setMinimumSize(QtCore.QSize(0, 20))
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_6.addWidget(self.label_4)
        self.label_5 = QtGui.QLabel(self.frame)
        self.label_5.setMinimumSize(QtCore.QSize(0, 20))
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_6.addWidget(self.label_5)
        self.horizontalLayout_3.addWidget(self.frame)
        self.frame_2 = QtGui.QFrame(self.frame_6)
        self.frame_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_anrede = QtGui.QLabel(self.frame_2)
        self.label_anrede.setMinimumSize(QtCore.QSize(0, 20))
        self.label_anrede.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_anrede.setText(_fromUtf8(""))
        self.label_anrede.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.label_anrede.setObjectName(_fromUtf8("label_anrede"))
        self.verticalLayout_3.addWidget(self.label_anrede)
        self.label_firma = QtGui.QLabel(self.frame_2)
        self.label_firma.setMinimumSize(QtCore.QSize(0, 20))
        self.label_firma.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_firma.setText(_fromUtf8(""))
        self.label_firma.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.label_firma.setObjectName(_fromUtf8("label_firma"))
        self.verticalLayout_3.addWidget(self.label_firma)
        self.label_vornachname = QtGui.QLabel(self.frame_2)
        self.label_vornachname.setMinimumSize(QtCore.QSize(0, 20))
        self.label_vornachname.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_vornachname.setText(_fromUtf8(""))
        self.label_vornachname.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.label_vornachname.setObjectName(_fromUtf8("label_vornachname"))
        self.verticalLayout_3.addWidget(self.label_vornachname)
        self.label_strasse = QtGui.QLabel(self.frame_2)
        self.label_strasse.setMinimumSize(QtCore.QSize(0, 20))
        self.label_strasse.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_strasse.setText(_fromUtf8(""))
        self.label_strasse.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.label_strasse.setObjectName(_fromUtf8("label_strasse"))
        self.verticalLayout_3.addWidget(self.label_strasse)
        self.label_plzort = QtGui.QLabel(self.frame_2)
        self.label_plzort.setMinimumSize(QtCore.QSize(0, 20))
        self.label_plzort.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_plzort.setText(_fromUtf8(""))
        self.label_plzort.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.label_plzort.setObjectName(_fromUtf8("label_plzort"))
        self.verticalLayout_3.addWidget(self.label_plzort)
        self.horizontalLayout_3.addWidget(self.frame_2)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout_8.addLayout(self.horizontalLayout_3)
        self.line = QtGui.QFrame(self.frame_6)
        font = QtGui.QFont()
        font.setKerning(True)
        self.line.setFont(font)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout_8.addWidget(self.line)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.frame_3 = QtGui.QFrame(self.frame_6)
        self.frame_3.setMinimumSize(QtCore.QSize(200, 0))
        self.frame_3.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.frame_3)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label_6 = QtGui.QLabel(self.frame_3)
        self.label_6.setMinimumSize(QtCore.QSize(0, 20))
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_5.addWidget(self.label_6)
        self.label_7 = QtGui.QLabel(self.frame_3)
        self.label_7.setMinimumSize(QtCore.QSize(0, 20))
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_5.addWidget(self.label_7)
        self.label_8 = QtGui.QLabel(self.frame_3)
        self.label_8.setMinimumSize(QtCore.QSize(0, 20))
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout_5.addWidget(self.label_8)
        self.label_9 = QtGui.QLabel(self.frame_3)
        self.label_9.setMinimumSize(QtCore.QSize(0, 20))
        self.label_9.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout_5.addWidget(self.label_9)
        self.horizontalLayout_4.addWidget(self.frame_3)
        self.frame_4 = QtGui.QFrame(self.frame_6)
        self.frame_4.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.frame_4)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.label_telefon = QtGui.QLabel(self.frame_4)
        self.label_telefon.setMinimumSize(QtCore.QSize(0, 20))
        self.label_telefon.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_telefon.setText(_fromUtf8(""))
        self.label_telefon.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.label_telefon.setObjectName(_fromUtf8("label_telefon"))
        self.verticalLayout_7.addWidget(self.label_telefon)
        self.label_mobil = QtGui.QLabel(self.frame_4)
        self.label_mobil.setMinimumSize(QtCore.QSize(0, 20))
        self.label_mobil.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_mobil.setText(_fromUtf8(""))
        self.label_mobil.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.label_mobil.setObjectName(_fromUtf8("label_mobil"))
        self.verticalLayout_7.addWidget(self.label_mobil)
        self.label_fax = QtGui.QLabel(self.frame_4)
        self.label_fax.setMinimumSize(QtCore.QSize(0, 20))
        self.label_fax.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_fax.setText(_fromUtf8(""))
        self.label_fax.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.label_fax.setObjectName(_fromUtf8("label_fax"))
        self.verticalLayout_7.addWidget(self.label_fax)
        self.label_email = QtGui.QLabel(self.frame_4)
        self.label_email.setMinimumSize(QtCore.QSize(0, 20))
        self.label_email.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_email.setText(_fromUtf8(""))
        self.label_email.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.label_email.setObjectName(_fromUtf8("label_email"))
        self.verticalLayout_7.addWidget(self.label_email)
        self.horizontalLayout_4.addWidget(self.frame_4)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout_8.addLayout(self.horizontalLayout_4)
        self.verticalLayout_12.addWidget(self.frame_6)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_11.addWidget(self.scrollArea)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.treeWidget_2 = QtGui.QTreeWidget(self.tab_2)
        self.treeWidget_2.setObjectName(_fromUtf8("treeWidget_2"))
        self.treeWidget_2.headerItem().setText(0, _fromUtf8("Projektnummer"))
        self.treeWidget_2.header().setCascadingSectionResizes(True)
        self.treeWidget_2.header().setDefaultSectionSize(200)
        self.treeWidget_2.header().setSortIndicatorShown(True)
        self.verticalLayout_2.addWidget(self.treeWidget_2)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.verticalLayout_4.addWidget(self.tabWidget)
        self.verticalLayout_10.addWidget(self.splitter)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_new.setText(QtGui.QApplication.translate("Form", "Neuer Kunde", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.setSortingEnabled(True)
        self.treeWidget.headerItem().setText(0, QtGui.QApplication.translate("Form", "Kunden Nr.", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.headerItem().setText(1, QtGui.QApplication.translate("Form", "Firma", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.headerItem().setText(2, QtGui.QApplication.translate("Form", "Nachname", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.headerItem().setText(3, QtGui.QApplication.translate("Form", "Vorname", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.headerItem().setText(4, QtGui.QApplication.translate("Form", "StraÃŸe", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.headerItem().setText(5, QtGui.QApplication.translate("Form", "Plz, Ort", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Form", "Anrede:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Form", "Firma:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Form", "Vorname/Nachname:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Form", "StraÃŸe:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Form", "PLZ, Ort", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Form", "Telefon:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Form", "Mobil:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Form", "Fax:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Form", "E-Mail:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("Form", "Details", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_2.headerItem().setText(1, QtGui.QApplication.translate("Form", "Projektname", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_2.headerItem().setText(2, QtGui.QApplication.translate("Form", "Status", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("Form", "AuftrÃ¤ge", None, QtGui.QApplication.UnicodeUTF8))

import res_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Form = QtGui.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

