# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'L:\Python Projekte\Galabau-2\Ui\Wizard\Belege\wizardPage.ui'
#
# Created: Thu Oct 11 00:38:14 2012
#      by: PyQt4 UI code generator 4.9.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_WizardPage(object):
    def setupUi(self, WizardPage):
        WizardPage.setObjectName(_fromUtf8("WizardPage"))
        WizardPage.resize(762, 443)
        self.verticalLayout_2 = QtGui.QVBoxLayout(WizardPage)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.widget_2 = QtGui.QWidget(WizardPage)
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.widget_2)
        self.verticalLayout_3.setSpacing(15)
        self.verticalLayout_3.setContentsMargins(-1, 20, -1, -1)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_artikelnr = QtGui.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_artikelnr.setFont(font)
        self.label_artikelnr.setObjectName(_fromUtf8("label_artikelnr"))
        self.verticalLayout_3.addWidget(self.label_artikelnr)
        self.line = QtGui.QFrame(self.widget_2)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout_3.addWidget(self.line)
        self.verticalLayout_2.addWidget(self.widget_2)
        self.widget = QtGui.QWidget(WizardPage)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.widget)
        self.label.setMinimumSize(QtCore.QSize(100, 0))
        self.label.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.input_Bezeichnung = QtGui.QComboBox(self.widget)
        self.input_Bezeichnung.setMinimumSize(QtCore.QSize(200, 0))
        self.input_Bezeichnung.setEditable(True)
        self.input_Bezeichnung.setObjectName(_fromUtf8("input_Bezeichnung"))
        self.horizontalLayout.addWidget(self.input_Bezeichnung)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_7 = QtGui.QLabel(self.widget)
        self.label_7.setMinimumSize(QtCore.QSize(100, 0))
        self.label_7.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_5.addWidget(self.label_7)
        self.input_Menge = QtGui.QLineEdit(self.widget)
        self.input_Menge.setObjectName(_fromUtf8("input_Menge"))
        self.horizontalLayout_5.addWidget(self.input_Menge)
        self.label_8 = QtGui.QLabel(self.widget)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_5.addWidget(self.label_8)
        self.input_Einheit = QtGui.QComboBox(self.widget)
        self.input_Einheit.setEditable(True)
        self.input_Einheit.setObjectName(_fromUtf8("input_Einheit"))
        self.horizontalLayout_5.addWidget(self.input_Einheit)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_4 = QtGui.QLabel(self.widget)
        self.label_4.setMinimumSize(QtCore.QSize(100, 0))
        self.label_4.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_4.addWidget(self.label_4)
        self.input_Betrag_Brutto_E = QtGui.QLineEdit(self.widget)
        self.input_Betrag_Brutto_E.setMaxLength(5)
        self.input_Betrag_Brutto_E.setObjectName(_fromUtf8("input_Betrag_Brutto_E"))
        self.horizontalLayout_4.addWidget(self.input_Betrag_Brutto_E)
        self.label_5 = QtGui.QLabel(self.widget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_4.addWidget(self.label_5)
        self.input_Betrag_Brutto_C = QtGui.QLineEdit(self.widget)
        self.input_Betrag_Brutto_C.setMaxLength(2)
        self.input_Betrag_Brutto_C.setObjectName(_fromUtf8("input_Betrag_Brutto_C"))
        self.horizontalLayout_4.addWidget(self.input_Betrag_Brutto_C)
        self.label_6 = QtGui.QLabel(self.widget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_4.addWidget(self.label_6)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_10 = QtGui.QLabel(self.widget)
        self.label_10.setMinimumSize(QtCore.QSize(100, 0))
        self.label_10.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_7.addWidget(self.label_10)
        self.input_Betrag_Netto_E = QtGui.QLineEdit(self.widget)
        self.input_Betrag_Netto_E.setMaxLength(5)
        self.input_Betrag_Netto_E.setObjectName(_fromUtf8("input_Betrag_Netto_E"))
        self.horizontalLayout_7.addWidget(self.input_Betrag_Netto_E)
        self.label_11 = QtGui.QLabel(self.widget)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_7.addWidget(self.label_11)
        self.input_Betrag_Netto_C = QtGui.QLineEdit(self.widget)
        self.input_Betrag_Netto_C.setMaxLength(2)
        self.input_Betrag_Netto_C.setObjectName(_fromUtf8("input_Betrag_Netto_C"))
        self.horizontalLayout_7.addWidget(self.input_Betrag_Netto_C)
        self.label_12 = QtGui.QLabel(self.widget)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_7.addWidget(self.label_12)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_3 = QtGui.QLabel(self.widget)
        self.label_3.setMinimumSize(QtCore.QSize(100, 0))
        self.label_3.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_3.addWidget(self.label_3)
        self.input_Projekt = QtGui.QLineEdit(self.widget)
        self.input_Projekt.setMinimumSize(QtCore.QSize(200, 0))
        self.input_Projekt.setReadOnly(True)
        self.input_Projekt.setObjectName(_fromUtf8("input_Projekt"))
        self.horizontalLayout_3.addWidget(self.input_Projekt)
        self.toolButton_Projekt = QtGui.QToolButton(self.widget)
        self.toolButton_Projekt.setObjectName(_fromUtf8("toolButton_Projekt"))
        self.horizontalLayout_3.addWidget(self.toolButton_Projekt)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_9 = QtGui.QLabel(self.widget)
        self.label_9.setMinimumSize(QtCore.QSize(100, 0))
        self.label_9.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_6.addWidget(self.label_9)
        self.input_Status = QtGui.QComboBox(self.widget)
        self.input_Status.setObjectName(_fromUtf8("input_Status"))
        self.input_Status.addItem(_fromUtf8(""))
        self.input_Status.addItem(_fromUtf8(""))
        self.input_Status.addItem(_fromUtf8(""))
        self.horizontalLayout_6.addWidget(self.input_Status)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem5)
        self.verticalLayout_2.addWidget(self.widget)

        self.retranslateUi(WizardPage)
        QtCore.QMetaObject.connectSlotsByName(WizardPage)

    def retranslateUi(self, WizardPage):
        WizardPage.setWindowTitle(QtGui.QApplication.translate("WizardPage", "WizardPage", None, QtGui.QApplication.UnicodeUTF8))
        WizardPage.setTitle(QtGui.QApplication.translate("WizardPage", "Position Nr. 1", None, QtGui.QApplication.UnicodeUTF8))
        WizardPage.setSubTitle(QtGui.QApplication.translate("WizardPage", "Beleg aufteilen nach Positionen", None, QtGui.QApplication.UnicodeUTF8))
        self.label_artikelnr.setText(QtGui.QApplication.translate("WizardPage", "Postion Nr. 1", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("WizardPage", "Bezeichnung:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("WizardPage", "Menge:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("WizardPage", "Einheit:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("WizardPage", "Betrag Brutto:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("WizardPage", "â‚¬", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("WizardPage", "Cent", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("WizardPage", "Betrag Netto:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("WizardPage", "â‚¬", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("WizardPage", "Cent", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("WizardPage", "Projekt:", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_Projekt.setText(QtGui.QApplication.translate("WizardPage", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("WizardPage", "Status:", None, QtGui.QApplication.UnicodeUTF8))
        self.input_Status.setItemText(0, QtGui.QApplication.translate("WizardPage", "Offen", None, QtGui.QApplication.UnicodeUTF8))
        self.input_Status.setItemText(1, QtGui.QApplication.translate("WizardPage", "Abgerechnet", None, QtGui.QApplication.UnicodeUTF8))
        self.input_Status.setItemText(2, QtGui.QApplication.translate("WizardPage", "Geld erhalten", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    WizardPage = QtGui.QWizardPage()
    ui = Ui_WizardPage()
    ui.setupUi(WizardPage)
    WizardPage.show()
    sys.exit(app.exec_())

