# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'L:\Python Projekte\Galabau-2\Ui\Wizard\Position\wizardStartPage.ui'
#
# Created: Thu Oct 11 00:38:18 2012
#      by: PyQt4 UI code generator 4.9.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_WizardPage(object):
    def setupUi(self, WizardPage):
        WizardPage.setObjectName(_fromUtf8("WizardPage"))
        WizardPage.resize(675, 411)
        self.verticalLayout = QtGui.QVBoxLayout(WizardPage)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.frame_2 = QtGui.QFrame(WizardPage)
        self.frame_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setSpacing(40)
        self.verticalLayout_3.setContentsMargins(-1, -1, -1, 9)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_datum = QtGui.QLabel(self.frame_2)
        self.label_datum.setMinimumSize(QtCore.QSize(300, 0))
        self.label_datum.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_datum.setFont(font)
        self.label_datum.setObjectName(_fromUtf8("label_datum"))
        self.horizontalLayout.addWidget(self.label_datum)
        self.label_anzahlak = QtGui.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_anzahlak.setFont(font)
        self.label_anzahlak.setObjectName(_fromUtf8("label_anzahlak"))
        self.horizontalLayout.addWidget(self.label_anzahlak)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_kunde = QtGui.QLabel(self.frame_2)
        self.label_kunde.setMinimumSize(QtCore.QSize(300, 0))
        self.label_kunde.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_kunde.setFont(font)
        self.label_kunde.setObjectName(_fromUtf8("label_kunde"))
        self.horizontalLayout_2.addWidget(self.label_kunde)
        self.label_projekt = QtGui.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_projekt.setFont(font)
        self.label_projekt.setObjectName(_fromUtf8("label_projekt"))
        self.horizontalLayout_2.addWidget(self.label_projekt)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.line = QtGui.QFrame(self.frame_2)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout_3.addWidget(self.line)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.frame = QtGui.QFrame(self.frame_2)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_2 = QtGui.QLabel(self.frame)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_2.addWidget(self.label_2)
        self.input_anzahlPos = QtGui.QComboBox(self.frame)
        self.input_anzahlPos.setObjectName(_fromUtf8("input_anzahlPos"))
        self.input_anzahlPos.addItem(_fromUtf8(""))
        self.input_anzahlPos.addItem(_fromUtf8(""))
        self.input_anzahlPos.addItem(_fromUtf8(""))
        self.input_anzahlPos.addItem(_fromUtf8(""))
        self.input_anzahlPos.addItem(_fromUtf8(""))
        self.input_anzahlPos.addItem(_fromUtf8(""))
        self.input_anzahlPos.addItem(_fromUtf8(""))
        self.input_anzahlPos.addItem(_fromUtf8(""))
        self.input_anzahlPos.addItem(_fromUtf8(""))
        self.input_anzahlPos.addItem(_fromUtf8(""))
        self.verticalLayout_2.addWidget(self.input_anzahlPos)
        self.verticalLayout_3.addWidget(self.frame)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.verticalLayout.addWidget(self.frame_2)

        self.retranslateUi(WizardPage)
        QtCore.QMetaObject.connectSlotsByName(WizardPage)

    def retranslateUi(self, WizardPage):
        WizardPage.setWindowTitle(QtGui.QApplication.translate("WizardPage", "WizardPage", None, QtGui.QApplication.UnicodeUTF8))
        WizardPage.setTitle(QtGui.QApplication.translate("WizardPage", "Positionen", None, QtGui.QApplication.UnicodeUTF8))
        WizardPage.setSubTitle(QtGui.QApplication.translate("WizardPage", "Stunden aufteilen nach Positionen", None, QtGui.QApplication.UnicodeUTF8))
        self.label_datum.setText(QtGui.QApplication.translate("WizardPage", "Datum", None, QtGui.QApplication.UnicodeUTF8))
        self.label_anzahlak.setText(QtGui.QApplication.translate("WizardPage", "Anzahl der Arbeiter", None, QtGui.QApplication.UnicodeUTF8))
        self.label_kunde.setText(QtGui.QApplication.translate("WizardPage", "Kunde", None, QtGui.QApplication.UnicodeUTF8))
        self.label_projekt.setText(QtGui.QApplication.translate("WizardPage", "Projekt", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("WizardPage", "Anzahl der Positionen auswÃ¤hlen:", None, QtGui.QApplication.UnicodeUTF8))
        self.input_anzahlPos.setItemText(0, QtGui.QApplication.translate("WizardPage", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.input_anzahlPos.setItemText(1, QtGui.QApplication.translate("WizardPage", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.input_anzahlPos.setItemText(2, QtGui.QApplication.translate("WizardPage", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.input_anzahlPos.setItemText(3, QtGui.QApplication.translate("WizardPage", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.input_anzahlPos.setItemText(4, QtGui.QApplication.translate("WizardPage", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.input_anzahlPos.setItemText(5, QtGui.QApplication.translate("WizardPage", "6", None, QtGui.QApplication.UnicodeUTF8))
        self.input_anzahlPos.setItemText(6, QtGui.QApplication.translate("WizardPage", "7", None, QtGui.QApplication.UnicodeUTF8))
        self.input_anzahlPos.setItemText(7, QtGui.QApplication.translate("WizardPage", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.input_anzahlPos.setItemText(8, QtGui.QApplication.translate("WizardPage", "9", None, QtGui.QApplication.UnicodeUTF8))
        self.input_anzahlPos.setItemText(9, QtGui.QApplication.translate("WizardPage", "10", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    WizardPage = QtGui.QWizardPage()
    ui = Ui_WizardPage()
    ui.setupUi(WizardPage)
    WizardPage.show()
    sys.exit(app.exec_())

