# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'L:\Python Projekte\Galabau-2\Ui\Wizard\Kunde\wizardPage.ui'
#
# Created: Thu Oct 11 00:38:15 2012
#      by: PyQt4 UI code generator 4.9.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_WizardPage(object):
    def setupUi(self, WizardPage):
        WizardPage.setObjectName(_fromUtf8("WizardPage"))
        WizardPage.resize(525, 296)
        self.verticalLayout_2 = QtGui.QVBoxLayout(WizardPage)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.frame = QtGui.QFrame(WizardPage)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.verticalLayout = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout.setSpacing(30)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.splitter_9 = QtGui.QSplitter(self.frame)
        self.splitter_9.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_9.setObjectName(_fromUtf8("splitter_9"))
        self.label_19 = QtGui.QLabel(self.splitter_9)
        self.label_19.setMinimumSize(QtCore.QSize(100, 0))
        self.label_19.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.input_AK = QtGui.QComboBox(self.splitter_9)
        self.input_AK.setEditable(True)
        self.input_AK.setFrame(True)
        self.input_AK.setObjectName(_fromUtf8("input_AK"))
        self.input_AK.addItem(_fromUtf8(""))
        self.input_AK.addItem(_fromUtf8(""))
        self.input_AK.addItem(_fromUtf8(""))
        self.verticalLayout.addWidget(self.splitter_9)
        self.splitter_16 = QtGui.QSplitter(self.frame)
        self.splitter_16.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_16.setObjectName(_fromUtf8("splitter_16"))
        self.label_12 = QtGui.QLabel(self.splitter_16)
        self.label_12.setMinimumSize(QtCore.QSize(100, 0))
        self.label_12.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.splitter_17 = QtGui.QSplitter(self.splitter_16)
        self.splitter_17.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.splitter_17.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_17.setHandleWidth(1)
        self.splitter_17.setObjectName(_fromUtf8("splitter_17"))
        self.input_StartH = QtGui.QComboBox(self.splitter_17)
        self.input_StartH.setObjectName(_fromUtf8("input_StartH"))
        self.input_StartH.addItem(_fromUtf8(""))
        self.input_StartH.addItem(_fromUtf8(""))
        self.input_StartH.addItem(_fromUtf8(""))
        self.input_StartH.addItem(_fromUtf8(""))
        self.input_StartH.addItem(_fromUtf8(""))
        self.input_StartH.addItem(_fromUtf8(""))
        self.input_StartH.addItem(_fromUtf8(""))
        self.input_StartH.addItem(_fromUtf8(""))
        self.input_StartH.addItem(_fromUtf8(""))
        self.input_StartH.addItem(_fromUtf8(""))
        self.input_StartH.addItem(_fromUtf8(""))
        self.input_StartH.addItem(_fromUtf8(""))
        self.input_StartH.addItem(_fromUtf8(""))
        self.input_StartH.addItem(_fromUtf8(""))
        self.input_StartH.addItem(_fromUtf8(""))
        self.input_StartH.addItem(_fromUtf8(""))
        self.input_StartH.addItem(_fromUtf8(""))
        self.input_StartH.addItem(_fromUtf8(""))
        self.input_StartH.addItem(_fromUtf8(""))
        self.input_StartH.addItem(_fromUtf8(""))
        self.input_StartH.addItem(_fromUtf8(""))
        self.input_StartH.addItem(_fromUtf8(""))
        self.input_StartH.addItem(_fromUtf8(""))
        self.input_StartH.addItem(_fromUtf8(""))
        self.input_StartH.addItem(_fromUtf8(""))
        self.splitter_18 = QtGui.QSplitter(self.splitter_17)
        self.splitter_18.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_18.setObjectName(_fromUtf8("splitter_18"))
        self.label_13 = QtGui.QLabel(self.splitter_18)
        self.label_13.setMaximumSize(QtCore.QSize(5, 16777215))
        self.label_13.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:1, stop:0 rgba(32, 66, 19, 0), stop:1 rgba(255, 255, 255, 255));"))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.input_StartM = QtGui.QComboBox(self.splitter_18)
        self.input_StartM.setObjectName(_fromUtf8("input_StartM"))
        self.input_StartM.addItem(_fromUtf8(""))
        self.input_StartM.addItem(_fromUtf8(""))
        self.input_StartM.addItem(_fromUtf8(""))
        self.input_StartM.addItem(_fromUtf8(""))
        self.verticalLayout.addWidget(self.splitter_16)
        self.splitter_19 = QtGui.QSplitter(self.frame)
        self.splitter_19.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_19.setObjectName(_fromUtf8("splitter_19"))
        self.label_14 = QtGui.QLabel(self.splitter_19)
        self.label_14.setMinimumSize(QtCore.QSize(100, 0))
        self.label_14.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.splitter_8 = QtGui.QSplitter(self.splitter_19)
        self.splitter_8.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.splitter_8.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_8.setHandleWidth(1)
        self.splitter_8.setObjectName(_fromUtf8("splitter_8"))
        self.input_EndeH = QtGui.QComboBox(self.splitter_8)
        self.input_EndeH.setObjectName(_fromUtf8("input_EndeH"))
        self.input_EndeH.addItem(_fromUtf8(""))
        self.input_EndeH.addItem(_fromUtf8(""))
        self.input_EndeH.addItem(_fromUtf8(""))
        self.input_EndeH.addItem(_fromUtf8(""))
        self.input_EndeH.addItem(_fromUtf8(""))
        self.input_EndeH.addItem(_fromUtf8(""))
        self.input_EndeH.addItem(_fromUtf8(""))
        self.input_EndeH.addItem(_fromUtf8(""))
        self.input_EndeH.addItem(_fromUtf8(""))
        self.input_EndeH.addItem(_fromUtf8(""))
        self.input_EndeH.addItem(_fromUtf8(""))
        self.input_EndeH.addItem(_fromUtf8(""))
        self.input_EndeH.addItem(_fromUtf8(""))
        self.input_EndeH.addItem(_fromUtf8(""))
        self.input_EndeH.addItem(_fromUtf8(""))
        self.input_EndeH.addItem(_fromUtf8(""))
        self.input_EndeH.addItem(_fromUtf8(""))
        self.input_EndeH.addItem(_fromUtf8(""))
        self.input_EndeH.addItem(_fromUtf8(""))
        self.input_EndeH.addItem(_fromUtf8(""))
        self.input_EndeH.addItem(_fromUtf8(""))
        self.input_EndeH.addItem(_fromUtf8(""))
        self.input_EndeH.addItem(_fromUtf8(""))
        self.input_EndeH.addItem(_fromUtf8(""))
        self.input_EndeH.addItem(_fromUtf8(""))
        self.splitter_20 = QtGui.QSplitter(self.splitter_8)
        self.splitter_20.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_20.setObjectName(_fromUtf8("splitter_20"))
        self.label_15 = QtGui.QLabel(self.splitter_20)
        self.label_15.setMaximumSize(QtCore.QSize(5, 16777215))
        self.label_15.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:1, stop:0 rgba(32, 66, 19, 0), stop:1 rgba(255, 255, 255, 255));"))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.input_EndeM = QtGui.QComboBox(self.splitter_20)
        self.input_EndeM.setObjectName(_fromUtf8("input_EndeM"))
        self.input_EndeM.addItem(_fromUtf8(""))
        self.input_EndeM.addItem(_fromUtf8(""))
        self.input_EndeM.addItem(_fromUtf8(""))
        self.input_EndeM.addItem(_fromUtf8(""))
        self.verticalLayout.addWidget(self.splitter_19)
        self.splitter_21 = QtGui.QSplitter(self.frame)
        self.splitter_21.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_21.setObjectName(_fromUtf8("splitter_21"))
        self.splitter_22 = QtGui.QSplitter(self.splitter_21)
        self.splitter_22.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.splitter_22.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_22.setHandleWidth(5)
        self.splitter_22.setObjectName(_fromUtf8("splitter_22"))
        self.label_16 = QtGui.QLabel(self.splitter_22)
        self.label_16.setMinimumSize(QtCore.QSize(100, 0))
        self.label_16.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.input_Pause = QtGui.QLineEdit(self.splitter_22)
        self.input_Pause.setText(_fromUtf8(""))
        self.input_Pause.setObjectName(_fromUtf8("input_Pause"))
        self.label_17 = QtGui.QLabel(self.splitter_21)
        self.label_17.setMaximumSize(QtCore.QSize(40, 20))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.verticalLayout.addWidget(self.splitter_21)
        self.splitter_5 = QtGui.QSplitter(self.frame)
        self.splitter_5.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_5.setObjectName(_fromUtf8("splitter_5"))
        self.label_20 = QtGui.QLabel(self.splitter_5)
        self.label_20.setMinimumSize(QtCore.QSize(100, 0))
        self.label_20.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.input_Status = QtGui.QComboBox(self.splitter_5)
        self.input_Status.setObjectName(_fromUtf8("input_Status"))
        self.input_Status.addItem(_fromUtf8(""))
        self.input_Status.addItem(_fromUtf8(""))
        self.verticalLayout.addWidget(self.splitter_5)
        self.verticalLayout_2.addWidget(self.frame)

        self.retranslateUi(WizardPage)
        QtCore.QMetaObject.connectSlotsByName(WizardPage)

    def retranslateUi(self, WizardPage):
        WizardPage.setWindowTitle(QtGui.QApplication.translate("WizardPage", "WizardPage", None, QtGui.QApplication.UnicodeUTF8))
        WizardPage.setTitle(QtGui.QApplication.translate("WizardPage", "Arbeiter", None, QtGui.QApplication.UnicodeUTF8))
        WizardPage.setSubTitle(QtGui.QApplication.translate("WizardPage", "Erfassen der AKs", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("WizardPage", "Arbeiter", None, QtGui.QApplication.UnicodeUTF8))
        self.input_AK.setItemText(0, QtGui.QApplication.translate("WizardPage", "Max", None, QtGui.QApplication.UnicodeUTF8))
        self.input_AK.setItemText(1, QtGui.QApplication.translate("WizardPage", "Johannes", None, QtGui.QApplication.UnicodeUTF8))
        self.input_AK.setItemText(2, QtGui.QApplication.translate("WizardPage", "David", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("WizardPage", "Arbeitsbeginn", None, QtGui.QApplication.UnicodeUTF8))
        self.input_StartH.setItemText(0, QtGui.QApplication.translate("WizardPage", "00", None, QtGui.QApplication.UnicodeUTF8))
        self.input_StartH.setItemText(1, QtGui.QApplication.translate("WizardPage", "01", None, QtGui.QApplication.UnicodeUTF8))
        self.input_StartH.setItemText(2, QtGui.QApplication.translate("WizardPage", "02", None, QtGui.QApplication.UnicodeUTF8))
        self.input_StartH.setItemText(3, QtGui.QApplication.translate("WizardPage", "03", None, QtGui.QApplication.UnicodeUTF8))
        self.input_StartH.setItemText(4, QtGui.QApplication.translate("WizardPage", "04", None, QtGui.QApplication.UnicodeUTF8))
        self.input_StartH.setItemText(5, QtGui.QApplication.translate("WizardPage", "05", None, QtGui.QApplication.UnicodeUTF8))
        self.input_StartH.setItemText(6, QtGui.QApplication.translate("WizardPage", "06", None, QtGui.QApplication.UnicodeUTF8))
        self.input_StartH.setItemText(7, QtGui.QApplication.translate("WizardPage", "07", None, QtGui.QApplication.UnicodeUTF8))
        self.input_StartH.setItemText(8, QtGui.QApplication.translate("WizardPage", "08", None, QtGui.QApplication.UnicodeUTF8))
        self.input_StartH.setItemText(9, QtGui.QApplication.translate("WizardPage", "09", None, QtGui.QApplication.UnicodeUTF8))
        self.input_StartH.setItemText(10, QtGui.QApplication.translate("WizardPage", "10", None, QtGui.QApplication.UnicodeUTF8))
        self.input_StartH.setItemText(11, QtGui.QApplication.translate("WizardPage", "11", None, QtGui.QApplication.UnicodeUTF8))
        self.input_StartH.setItemText(12, QtGui.QApplication.translate("WizardPage", "12", None, QtGui.QApplication.UnicodeUTF8))
        self.input_StartH.setItemText(13, QtGui.QApplication.translate("WizardPage", "13", None, QtGui.QApplication.UnicodeUTF8))
        self.input_StartH.setItemText(14, QtGui.QApplication.translate("WizardPage", "14", None, QtGui.QApplication.UnicodeUTF8))
        self.input_StartH.setItemText(15, QtGui.QApplication.translate("WizardPage", "15", None, QtGui.QApplication.UnicodeUTF8))
        self.input_StartH.setItemText(16, QtGui.QApplication.translate("WizardPage", "16", None, QtGui.QApplication.UnicodeUTF8))
        self.input_StartH.setItemText(17, QtGui.QApplication.translate("WizardPage", "17", None, QtGui.QApplication.UnicodeUTF8))
        self.input_StartH.setItemText(18, QtGui.QApplication.translate("WizardPage", "18", None, QtGui.QApplication.UnicodeUTF8))
        self.input_StartH.setItemText(19, QtGui.QApplication.translate("WizardPage", "19", None, QtGui.QApplication.UnicodeUTF8))
        self.input_StartH.setItemText(20, QtGui.QApplication.translate("WizardPage", "20", None, QtGui.QApplication.UnicodeUTF8))
        self.input_StartH.setItemText(21, QtGui.QApplication.translate("WizardPage", "21", None, QtGui.QApplication.UnicodeUTF8))
        self.input_StartH.setItemText(22, QtGui.QApplication.translate("WizardPage", "22", None, QtGui.QApplication.UnicodeUTF8))
        self.input_StartH.setItemText(23, QtGui.QApplication.translate("WizardPage", "23", None, QtGui.QApplication.UnicodeUTF8))
        self.input_StartH.setItemText(24, QtGui.QApplication.translate("WizardPage", "24", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("WizardPage", ":", None, QtGui.QApplication.UnicodeUTF8))
        self.input_StartM.setItemText(0, QtGui.QApplication.translate("WizardPage", "00", None, QtGui.QApplication.UnicodeUTF8))
        self.input_StartM.setItemText(1, QtGui.QApplication.translate("WizardPage", "15", None, QtGui.QApplication.UnicodeUTF8))
        self.input_StartM.setItemText(2, QtGui.QApplication.translate("WizardPage", "30", None, QtGui.QApplication.UnicodeUTF8))
        self.input_StartM.setItemText(3, QtGui.QApplication.translate("WizardPage", "45", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("WizardPage", "Arbeitsende", None, QtGui.QApplication.UnicodeUTF8))
        self.input_EndeH.setItemText(0, QtGui.QApplication.translate("WizardPage", "00", None, QtGui.QApplication.UnicodeUTF8))
        self.input_EndeH.setItemText(1, QtGui.QApplication.translate("WizardPage", "01", None, QtGui.QApplication.UnicodeUTF8))
        self.input_EndeH.setItemText(2, QtGui.QApplication.translate("WizardPage", "02", None, QtGui.QApplication.UnicodeUTF8))
        self.input_EndeH.setItemText(3, QtGui.QApplication.translate("WizardPage", "03", None, QtGui.QApplication.UnicodeUTF8))
        self.input_EndeH.setItemText(4, QtGui.QApplication.translate("WizardPage", "04", None, QtGui.QApplication.UnicodeUTF8))
        self.input_EndeH.setItemText(5, QtGui.QApplication.translate("WizardPage", "05", None, QtGui.QApplication.UnicodeUTF8))
        self.input_EndeH.setItemText(6, QtGui.QApplication.translate("WizardPage", "06", None, QtGui.QApplication.UnicodeUTF8))
        self.input_EndeH.setItemText(7, QtGui.QApplication.translate("WizardPage", "07", None, QtGui.QApplication.UnicodeUTF8))
        self.input_EndeH.setItemText(8, QtGui.QApplication.translate("WizardPage", "08", None, QtGui.QApplication.UnicodeUTF8))
        self.input_EndeH.setItemText(9, QtGui.QApplication.translate("WizardPage", "09", None, QtGui.QApplication.UnicodeUTF8))
        self.input_EndeH.setItemText(10, QtGui.QApplication.translate("WizardPage", "10", None, QtGui.QApplication.UnicodeUTF8))
        self.input_EndeH.setItemText(11, QtGui.QApplication.translate("WizardPage", "11", None, QtGui.QApplication.UnicodeUTF8))
        self.input_EndeH.setItemText(12, QtGui.QApplication.translate("WizardPage", "12", None, QtGui.QApplication.UnicodeUTF8))
        self.input_EndeH.setItemText(13, QtGui.QApplication.translate("WizardPage", "13", None, QtGui.QApplication.UnicodeUTF8))
        self.input_EndeH.setItemText(14, QtGui.QApplication.translate("WizardPage", "14", None, QtGui.QApplication.UnicodeUTF8))
        self.input_EndeH.setItemText(15, QtGui.QApplication.translate("WizardPage", "15", None, QtGui.QApplication.UnicodeUTF8))
        self.input_EndeH.setItemText(16, QtGui.QApplication.translate("WizardPage", "16", None, QtGui.QApplication.UnicodeUTF8))
        self.input_EndeH.setItemText(17, QtGui.QApplication.translate("WizardPage", "17", None, QtGui.QApplication.UnicodeUTF8))
        self.input_EndeH.setItemText(18, QtGui.QApplication.translate("WizardPage", "18", None, QtGui.QApplication.UnicodeUTF8))
        self.input_EndeH.setItemText(19, QtGui.QApplication.translate("WizardPage", "19", None, QtGui.QApplication.UnicodeUTF8))
        self.input_EndeH.setItemText(20, QtGui.QApplication.translate("WizardPage", "20", None, QtGui.QApplication.UnicodeUTF8))
        self.input_EndeH.setItemText(21, QtGui.QApplication.translate("WizardPage", "21", None, QtGui.QApplication.UnicodeUTF8))
        self.input_EndeH.setItemText(22, QtGui.QApplication.translate("WizardPage", "22", None, QtGui.QApplication.UnicodeUTF8))
        self.input_EndeH.setItemText(23, QtGui.QApplication.translate("WizardPage", "23", None, QtGui.QApplication.UnicodeUTF8))
        self.input_EndeH.setItemText(24, QtGui.QApplication.translate("WizardPage", "24", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("WizardPage", ":", None, QtGui.QApplication.UnicodeUTF8))
        self.input_EndeM.setItemText(0, QtGui.QApplication.translate("WizardPage", "00", None, QtGui.QApplication.UnicodeUTF8))
        self.input_EndeM.setItemText(1, QtGui.QApplication.translate("WizardPage", "15", None, QtGui.QApplication.UnicodeUTF8))
        self.input_EndeM.setItemText(2, QtGui.QApplication.translate("WizardPage", "30", None, QtGui.QApplication.UnicodeUTF8))
        self.input_EndeM.setItemText(3, QtGui.QApplication.translate("WizardPage", "45", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("WizardPage", "Pause", None, QtGui.QApplication.UnicodeUTF8))
        self.input_Pause.setStyleSheet(QtGui.QApplication.translate("WizardPage", "background-color: rgb(255, 255, 255);", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("WizardPage", "Minuten", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("WizardPage", "Status", None, QtGui.QApplication.UnicodeUTF8))
        self.input_Status.setItemText(0, QtGui.QApplication.translate("WizardPage", "Offen", None, QtGui.QApplication.UnicodeUTF8))
        self.input_Status.setItemText(1, QtGui.QApplication.translate("WizardPage", "Ausgezahlt", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    WizardPage = QtGui.QWizardPage()
    ui = Ui_WizardPage()
    ui.setupUi(WizardPage)
    WizardPage.show()
    sys.exit(app.exec_())

