# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'L:\Python Projekte\Galabau-2\Ui\mainwindow.ui'
#
# Created: Thu Oct 11 00:38:05 2012
#      by: PyQt4 UI code generator 4.9.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(977, 680)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/newPrefix/res/100px_logo_galabau.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setToolTip(_fromUtf8(""))
        MainWindow.setAutoFillBackground(False)
        MainWindow.setDocumentMode(True)
        MainWindow.setTabShape(QtGui.QTabWidget.Rounded)
        MainWindow.setDockNestingEnabled(True)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.centralWidget)
        self.horizontalLayout_2.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.frame_2 = QtGui.QFrame(self.centralWidget)
        self.frame_2.setMinimumSize(QtCore.QSize(700, 0))
        self.frame_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.frame_2)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setMargin(0)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout_2.addWidget(self.frame_2)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 977, 18))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuDatei = QtGui.QMenu(self.menuBar)
        self.menuDatei.setObjectName(_fromUtf8("menuDatei"))
        self.menuWirtschaftsjahr_wechseln = QtGui.QMenu(self.menuDatei)
        self.menuWirtschaftsjahr_wechseln.setObjectName(_fromUtf8("menuWirtschaftsjahr_wechseln"))
        self.menuAnsicht = QtGui.QMenu(self.menuBar)
        self.menuAnsicht.setObjectName(_fromUtf8("menuAnsicht"))
        self.menuExtras = QtGui.QMenu(self.menuBar)
        self.menuExtras.setObjectName(_fromUtf8("menuExtras"))
        self.menuEinstellungen = QtGui.QMenu(self.menuBar)
        self.menuEinstellungen.setObjectName(_fromUtf8("menuEinstellungen"))
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setSizeGripEnabled(True)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolBar.setFloatable(False)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.dockWidget = QtGui.QDockWidget(MainWindow)
        self.dockWidget.setObjectName(_fromUtf8("dockWidget"))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.dockWidget.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockWidget)
        self.actionL_schen = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/newPrefix/res/Private Folder.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionL_schen.setIcon(icon1)
        self.actionL_schen.setObjectName(_fromUtf8("actionL_schen"))
        self.actionKunden = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/newPrefix/res/Users Folder.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionKunden.setIcon(icon2)
        self.actionKunden.setIconVisibleInMenu(True)
        self.actionKunden.setObjectName(_fromUtf8("actionKunden"))
        self.actionProjekte = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/newPrefix/res/Project-icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionProjekte.setIcon(icon3)
        self.actionProjekte.setObjectName(_fromUtf8("actionProjekte"))
        self.actionArbeitsstunden = QtGui.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/newPrefix/res/1318969250_gnome-planner.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionArbeitsstunden.setIcon(icon4)
        self.actionArbeitsstunden.setObjectName(_fromUtf8("actionArbeitsstunden"))
        self.actionBelege = QtGui.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/newPrefix/res/Documents Folder.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionBelege.setIcon(icon5)
        self.actionBelege.setObjectName(_fromUtf8("actionBelege"))
        self.actionOptionen = QtGui.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/newPrefix/res/Settings.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOptionen.setIcon(icon6)
        self.actionOptionen.setObjectName(_fromUtf8("actionOptionen"))
        self.actionEinstellungen_speichern = QtGui.QAction(MainWindow)
        self.actionEinstellungen_speichern.setObjectName(_fromUtf8("actionEinstellungen_speichern"))
        self.actionEinstellungen_laden = QtGui.QAction(MainWindow)
        self.actionEinstellungen_laden.setObjectName(_fromUtf8("actionEinstellungen_laden"))
        self.action2011 = QtGui.QAction(MainWindow)
        self.action2011.setCheckable(True)
        self.action2011.setChecked(True)
        self.action2011.setObjectName(_fromUtf8("action2011"))
        self.action2012 = QtGui.QAction(MainWindow)
        self.action2012.setCheckable(True)
        self.action2012.setObjectName(_fromUtf8("action2012"))
        self.menuWirtschaftsjahr_wechseln.addAction(self.action2011)
        self.menuWirtschaftsjahr_wechseln.addAction(self.action2012)
        self.menuDatei.addAction(self.menuWirtschaftsjahr_wechseln.menuAction())
        self.menuAnsicht.addAction(self.actionKunden)
        self.menuAnsicht.addAction(self.actionProjekte)
        self.menuAnsicht.addAction(self.actionArbeitsstunden)
        self.menuAnsicht.addAction(self.actionBelege)
        self.menuEinstellungen.addAction(self.actionOptionen)
        self.menuEinstellungen.addSeparator()
        self.menuEinstellungen.addAction(self.actionEinstellungen_speichern)
        self.menuEinstellungen.addAction(self.actionEinstellungen_laden)
        self.menuBar.addAction(self.menuDatei.menuAction())
        self.menuBar.addAction(self.menuAnsicht.menuAction())
        self.menuBar.addAction(self.menuEinstellungen.menuAction())
        self.menuBar.addAction(self.menuExtras.menuAction())
        self.toolBar.addAction(self.actionKunden)
        self.toolBar.addAction(self.actionProjekte)
        self.toolBar.addAction(self.actionArbeitsstunden)
        self.toolBar.addAction(self.actionBelege)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "GalaBau", None, QtGui.QApplication.UnicodeUTF8))
        self.menuDatei.setTitle(QtGui.QApplication.translate("MainWindow", "Datei", None, QtGui.QApplication.UnicodeUTF8))
        self.menuWirtschaftsjahr_wechseln.setTitle(QtGui.QApplication.translate("MainWindow", "Wirtschaftsjahr wechseln", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAnsicht.setTitle(QtGui.QApplication.translate("MainWindow", "Ansicht", None, QtGui.QApplication.UnicodeUTF8))
        self.menuExtras.setTitle(QtGui.QApplication.translate("MainWindow", "Extras", None, QtGui.QApplication.UnicodeUTF8))
        self.menuEinstellungen.setTitle(QtGui.QApplication.translate("MainWindow", "Einstellungen", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionL_schen.setText(QtGui.QApplication.translate("MainWindow", "LÃ¶schen", None, QtGui.QApplication.UnicodeUTF8))
        self.actionKunden.setText(QtGui.QApplication.translate("MainWindow", "Kunden", None, QtGui.QApplication.UnicodeUTF8))
        self.actionProjekte.setText(QtGui.QApplication.translate("MainWindow", "Projekte", None, QtGui.QApplication.UnicodeUTF8))
        self.actionArbeitsstunden.setText(QtGui.QApplication.translate("MainWindow", "Arbeitsstunden", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBelege.setText(QtGui.QApplication.translate("MainWindow", "Belege", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBelege.setToolTip(QtGui.QApplication.translate("MainWindow", "Belege", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOptionen.setText(QtGui.QApplication.translate("MainWindow", "Optionen", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEinstellungen_speichern.setText(QtGui.QApplication.translate("MainWindow", "Einstellungen speichern", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEinstellungen_laden.setText(QtGui.QApplication.translate("MainWindow", "Einstellungen laden", None, QtGui.QApplication.UnicodeUTF8))
        self.action2011.setText(QtGui.QApplication.translate("MainWindow", "2011", None, QtGui.QApplication.UnicodeUTF8))
        self.action2012.setText(QtGui.QApplication.translate("MainWindow", "2012", None, QtGui.QApplication.UnicodeUTF8))

import res_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

